name: Bahdashcyh on Security - Front build and deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }};
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }};
          aws configure set region eu-central-1;

      - name: Setting environment variables
        run: |
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
          echo "AWS_FRONT_SG_NAME=bahdashych-on-security-front" >> $GITHUB_ENV

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_FRONT_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32;

      - name: Create the .ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh
      - name: Install the deploy key for the front-end
        run: echo "${{ secrets.FE_DEPLOY_KEY }}" >> ~/.ssh/fe_deploy && chmod 600 ~/.ssh/fe_deploy
      - name: Create the known hosts file
        run: echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Remotely trigger building and deployment script for the front-end
        run: ssh -i ~/.ssh/fe_deploy deployer@${{ secrets.FE_HOST_IP }}

      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_FRONT_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32;
        if: always()
